import { PostState, Project } from '@/types/types';

export const PROJECTS: Project[] = [
  {
    id: 1,
    author: '김기획',
    start: new Date(),
    end: new Date(),
    position: '프론트엔드',
    tags: ['AI', '금융', '자율주행'],
    stacks: ['recoil', 'java'],
    jobs: [
      { 프론트엔드: { want: 3, current: 0 } },
      { 백엔드: { want: 3, current: 1 } },
    ],
    title: '한국 투자 증권 api로 플젝 해보실분?!!?',
    content:
      '우리 프로젝트 같이 하실분 구해요!!!!\n\n\n```\nconst Main = styled.div`\n  padding: var(--padding-1);\n  display: flex;\n``` \n # ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
    state: 1, // 1=모집 중, 2=모집 완료, 3=종료
    createAt: '2023-04-01T11:50:29.769Z',
    view: 500,
    heart: 10,
    comment: [],
  },
  {
    id: 2,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 3,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 4,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 5,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 6,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 7,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 8,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 9,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 10,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 11,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 12,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 13,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 14,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 15,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 16,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 17,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 18,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 19,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 20,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 21,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 22,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 23,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 24,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 25,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 26,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 27,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 28,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 29,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 30,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 31,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
  {
    id: 32,
    author: '박디자인',
    start: new Date(),
    end: new Date(),
    tags: ['UI/UX', '웹', '앱'],
    stacks: ['react', 'figma'],
    jobs: [
      { 디자이너: { want: 2, current: 1 } },
      { 백엔드: { want: 1, current: 0 } },
    ],
    title: '시작부터 끝까지! 웹/앱 UI/UX 디자인 플젝',
    content:
      '우리 같이 디자인 끝까지 해봅시다.\n\n\n```\nconst Section = styled.section`\n  display: flex;\n  align-items: center;\n  justify-content: center;\n``` \n # Figma # Sketch # AdobeXD',
    state: 1,
    createAt: '2023-04-05T11:50:29.769Z',
    view: 20,
    heart: 5,
    comment: [],
  },
];

export const POST_STATE: PostState[] = [
  {
    id: 1,
    heart: true,
    want: '백엔드',
  },
  {
    id: 2,
    heart: false,
    want: '',
  },
  {
    id: 3,
    heart: true,
    want: '',
  },
  {
    id: 4,
    heart: false,
    want: '',
  },
  {
    id: 5,
    heart: true,
    want: '',
  },
  {
    id: 6,
    heart: false,
    want: '',
  },
  {
    id: 7,
    heart: true,
    want: '',
  },
  {
    id: 8,
    heart: false,
    want: '',
  },
  {
    id: 9,
    heart: true,
    want: '',
  },
  {
    id: 10,
    heart: false,
    want: '',
  },
  {
    id: 11,
    heart: false,
    want: '',
  },
  {
    id: 12,
    heart: true,
    want: '',
  },
  {
    id: 13,
    heart: false,
    want: '',
  },
  {
    id: 14,
    heart: false,
    want: '',
  },
  {
    id: 15,
    heart: false,
    want: '',
  },
  {
    id: 16,
    heart: true,
    want: '',
  },
  {
    id: 17,
    heart: false,
    want: '',
  },
  {
    id: 18,
    heart: false,
    want: '',
  },
  {
    id: 19,
    heart: true,
    want: '',
  },
  {
    id: 20,
    heart: false,
    want: '',
  },
  {
    id: 21,
    heart: false,
    want: '',
  },
  {
    id: 22,
    heart: false,
    want: '',
  },
  {
    id: 23,
    heart: false,
    want: '',
  },
  {
    id: 24,
    heart: true,
    want: '',
  },
  {
    id: 25,
    heart: false,
    want: '',
  },
  {
    id: 26,
    heart: false,
    want: '',
  },
  {
    id: 27,
    heart: false,
    want: '',
  },
  {
    id: 28,
    heart: false,
    want: '',
  },
  {
    id: 29,
    heart: true,
    want: '',
  },
  {
    id: 30,
    heart: false,
    want: '',
  },
  {
    id: 31,
    heart: false,
    want: '',
  },
  {
    id: 32,
    heart: true,
    want: '',
  },
];
